### ISSUE TITLE
PaddleScience cylinder3d_unsteady.py core dumped

### ISSUE THREAD

**Issue by zzk0** [PaddlePaddle/CINN#1321]
# error log

```
λ ubuntu /PaddleScience {develop} bash /CINN/workspace/paddle_science/run.sh
/PaddleScience/paddlescience/neo_geometry/mesh.py:26: UserWarning: Refer to README.md and install pymesh before using mesh API in neo_geometry
  "Refer to README.md and install pymesh before using mesh API in neo_geometry"
/PaddleScience/paddlescience/neo_geometry/inflation.py:24: UserWarning: Refer to README.md and install open3d and pymesh before using inflation API in neo_geometry
  f"Refer to README.md and install open3d and pymesh before using inflation API in neo_geometry"
100% [..........................................................................] 1055986 / 1055986I0331 07:39:51.424743 1017636 interpretercore.cc:282] New Executor is Running.
W0331 07:39:51.426287 1017636 gpu_resources.cc:85] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.8, Runtime API Version: 11.2
W0331 07:39:51.429787 1017636 gpu_resources.cc:115] device: 0, cuDNN Version: 8.1.
### train next time=101.000000 train task ###
Static Graph is Currently in Use.
Optimized AD is Currently in Use
CINN is currently used.
/usr/local/lib/python3.7/dist-packages/paddle/fluid/compiler.py:243: UserWarning: At present, when CINN is turned on, each process can only contain one thread, so reset the number of threads to 1 here.
  "At present, when CINN is turned on, each process can "
I0331 07:48:20.028909 1017636 build_cinn_pass.cc:682] --- [build_cinn_pass] detected 97 cinn supported subgraphs
F0331 07:48:23.657730 1017636 elementwise.cc:329] Check failed: !shape.empty() shape attr is empty!
*** Check failure stack trace: ***
    @     0x7f231b4b15ed  google::LogMessage::Fail()
    @     0x7f231b4b389d  google::LogMessage::SendToLog()
    @     0x7f231b4b10dd  google::LogMessage::Flush()
    @     0x7f231b4b4399  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f230fff48fa  cinn::hlir::op::InferShapeForFillConstant()
    @     0x7f230ff233db  std::_Function_handler<>::_M_invoke()
    @     0x7f231004675c  std::function<>::operator()()
    @     0x7f23101326ea  cinn::frontend::NetBuilder::InferShape()
    @     0x7f2310132bbe  cinn::frontend::NetBuilder::CustomInstr()
    @     0x7f2310136ff5  cinn::frontend::NetBuilder::FillConstant()
    @     0x7f2310224720  cinn::frontend::science_mappers::FillConstantOpMapper()
    @     0x7f2310194ad2  std::_Function_handler<>::_M_invoke()
    @     0x7f231eaae44e  paddle::framework::paddle2cinn::CinnGraphSymbolization::RunOp()
    @     0x7f231eab0ab7  paddle::framework::paddle2cinn::CinnGraphSymbolization::RunGraph()
    @     0x7f231eab172b  paddle::framework::paddle2cinn::CinnGraphSymbolization::operator()()
    @     0x7f231e94c164  paddle::framework::paddle2cinn::CinnCompiler::CompileGraph()
    @     0x7f231e94e5ae  paddle::framework::paddle2cinn::CinnCompiler::Compile()
    @     0x7f231d0f2fb0  paddle::operators::CinnLaunchOpKernel<>::Compute()
    @     0x7f231d0f5934  _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorIN3phi8GPUPlaceELb0ELm0EJNS0_9operators18CinnLaunchOpKernelINS7_10GPUContextEfEEEEclEPKcSF_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
    @     0x7f231eb946c9  paddle::framework::interpreter::BuildOpFuncList()
    @     0x7f231b7e5140  paddle::framework::InterpreterCore::Run()
    @     0x7f231b7f2618  paddle::framework::StandaloneExecutor::Run()
    @     0x7f231b1888a2  _ZZN8pybind1112cpp_function10initializeIZN6paddle6pybindL23pybind11_init_libpaddleERNS_7module_EEUlRNS2_9framework18StandaloneExecutorEPNS6_5ScopeESt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISH_EESJ_E105_NS_6objectEJS8_SA_SJ_SJ_EJNS_4nameENS_9is_methodENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNES12_
    @     0x7f231af68f33  pybind11::cpp_function::dispatcher()
    @     0x55f7be159c38  _PyObject_FastCallKeywords
    @     0x55f7be1cd63d  _PyEval_EvalFrameDefault
    @     0x55f7be1c7b0e  _PyEval_EvalCodeWithName
    @     0x55f7be15a77a  _PyFunction_FastCallKeywords
    @     0x55f7be1c8c9e  _PyEval_EvalFrameDefault
    @     0x55f7be1c7b0e  _PyEval_EvalCodeWithName
    @     0x55f7be15a77a  _PyFunction_FastCallKeywords
    @     0x55f7be1c986a  _PyEval_EvalFrameDefault
/CINN/workspace/paddle_science/run.sh: line 7: 1017636 Aborted                 (core dumped) python3.7 examples/cylinder/3d_unsteady_discrete/baseline/cylinder3d_unsteady.py -c tests/config/cylinder3d_unsteady.yaml
```

**Comment by zzk0** [comment]
打印 log，发现部分算子缺失 shape 的数据：

![image](https://user-images.githubusercontent.com/30856589/229071686-7564a3c4-4225-4987-82b5-714838857352.png)

```
  ops {
    outputs {
      parameter: "Y"
      arguments: "tmp_7"
    }
    type: "fill_constant_p"
    attrs {
      name: "dtype"
      type: INT
      i: 5
    }
    attrs {
      name: "op_callstack"
      type: STRINGS
      strings: "  File \"examples/cylinder/3d_unsteady_discrete/baseline/cylinder3d_unsteady.py\", line 154, in <module>"
      strings: "    solver = psci.solver.Solver(pde=pde_disc, algo=algo, opt=opt)"
      strings: "  File \"/PaddleScience/paddlescience/solver/solver.py\", line 143, in __init__"
      strings: "    self.__init_static()"
      strings: "  File \"/PaddleScience/paddlescience/solver/solver.py\", line 584, in __init_static"
      strings: "    self.opt.minimize(self.loss)"
      strings: "  File \"<decorator-gen-187>\", line 2, in minimize"
      strings: "    "
      strings: "  File \"/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py\", line 353, in _decorate_function"
      strings: "    return func(*args, **kwargs)"
      strings: "  File \"/usr/local/lib/python3.7/dist-packages/paddle/optimizer/optimizer.py\", line 1436, in minimize"
      strings: "    no_grad_set=no_grad_set,"
      strings: "  File \"/usr/local/lib/python3.7/dist-packages/paddle/optimizer/optimizer.py\", line 1123, in backward"
      strings: "    [loss], parameter_list, act_no_grad_set, callbacks"
      strings: "  File \"<decorator-gen-177>\", line 2, in append_backward_new"
      strings: "    "
      strings: "  File \"/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py\", line 25, in __impl__"
      strings: "    return wrapped_func(*args, **kwargs)"
      strings: "  File \"/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py\", line 626, in __impl__"
      strings: "    return func(*args, **kwargs)"
      strings: "  File \"/usr/local/lib/python3.7/dist-packages/paddle/optimizer/optimizer.py\", line 64, in append_backward_new"
      strings: "    orig2prim(block)"
      strings: "  File \"<decorator-gen-220>\", line 2, in orig2prim"
      strings: "    "
      strings: "  File \"/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py\", line 25, in __impl__"
      strings: "    return wrapped_func(*args, **kwargs)"
      strings: "  File \"/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py\", line 626, in __impl__"
      strings: "    return func(*args, **kwargs)"
      strings: "  File \"/usr/local/lib/python3.7/dist-packages/paddle/incubate/autograd/primx.py\", line 722, in orig2prim"
      strings: "    _lower(block, reverse=False, blacklist=[])"
      strings: "  File \"/usr/local/lib/python3.7/dist-packages/paddle/incubate/autograd/primx.py\", line 523, in _lower"
      strings: "    attrs=attrs,"
      strings: "  File \"/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py\", line 2977, in __init__"
      strings: "    for frame in traceback.extract_stack():"
    }
    attrs {
      name: "op_device"
      type: STRING
      s: ""
    }
    attrs {
      name: "op_namescope"
      type: STRING
      s: "/"
    }
    attrs {
      name: "op_role"
      type: INT
      i: 0
    }
    attrs {
      name: "op_role_var"
      type: STRINGS
    }
    attrs {
      name: "shape"
      type: LONGS
     !!!!!!! 这里缺失
    }
    attrs {
      name: "value"
      type: FLOAT
      f: 2
    }
    attrs {
      name: "with_quant_attr"
      type: BOOLEAN
      b: false
    }
  }
```

**Comment by zzk0** [comment]
Paddle 里面是允许将 shape 设置为 [] 的，可能这个 shape 为 [] 的 var 是一个 [placeholder](https://stackoverflow.com/questions/47674588/tensorflow-how-create-an-const-tensor-the-same-shape-as-a-placeholder)

## fill_constant_p 算子

没有提供实现，使用 prim2orig 的流程将它推给 paddle 执行（我猜

```
class FillConstantPrimOp : public framework::OperatorBase {
 public:
  FillConstantPrimOp(const std::string &type,
                     const framework::VariableNameMap &inputs,
                     const framework::VariableNameMap &outputs,
                     const framework::AttributeMap &attrs)
      : framework::OperatorBase(type, inputs, outputs, attrs) {}
  void RunImpl(const framework::Scope &scope,
               const platform::Place &dev_place) const override {
    PADDLE_THROW(platform::errors::Unimplemented(
        "Prim operator fill_constant_p should not be excuted directly"));
  }
};
```

## fill_constant 算子

```
class FillConstantOp : public framework::OperatorWithKernel {
 public:
  using framework::OperatorWithKernel::OperatorWithKernel;

  void InferShape(framework::InferShapeContext *ctx) const override {
    OP_INOUT_CHECK(ctx->HasOutput("Out"), "Output", "Out", "FillConstant");

    auto &shape = ctx->Attrs().Get<std::vector<int64_t>>("shape");
    if (!ctx->HasInput("ShapeTensor") && !ctx->HasInputs("ShapeTensorList")) {
      for (size_t i = 0; i < shape.size(); ++i) {
        PADDLE_ENFORCE_GE(
            shape[i],
            0,
            platform::errors::InvalidArgument(
                "Each value of attribute 'shape' is expected to be no less "
                "than 0. But received: shape[%u] = %d; shape = [%s].",
                i,
                shape[i],
                phi::make_ddim(shape)));
      }
    }
    if (shape.empty() && ctx->HasInput("ShapeTensor")) {
      auto shape_dims = ctx->GetInputDim("ShapeTensor");
      int num_ele = 1;
      for (int i = 0; i < shape_dims.size(); ++i) {
        num_ele *= shape_dims[i];
      }
      auto vec_dims = std::vector<int>(num_ele, -1);
      ctx->SetOutputDim("Out", phi::make_ddim(vec_dims));

      return;
    }
    ctx->SetOutputDim("Out", phi::make_ddim(shape));
  }

 protected:
  phi::KernelKey GetKernelTypeForVar(
      const std::string &var_name,
      const phi::DenseTensor &tensor,
      const phi::KernelKey &expected_kernel_type) const override {
    if (var_name == "ShapeTensor" || var_name == "ShapeTensorList") {
      return phi::KernelKey(phi::Backend::ALL_BACKEND,
                            expected_kernel_type.layout(),
                            expected_kernel_type.dtype());
    } else {
      return phi::KernelKey(
          tensor.place(), tensor.layout(), expected_kernel_type.dtype());
    }
  }

  phi::KernelKey GetExpectedKernelType(
      const framework::ExecutionContext &ctx) const override {
    auto input_data_type =
        framework::proto::VarType::Type(ctx.Attr<int>("dtype"));
    phi::KernelKey kt = phi::KernelKey(input_data_type, ctx.GetPlace());
    // TODO(zyfncg) The force_cpu and place_type are conflicted, it's an issue
    // left before, and we may merge them in the future.
    // In order to invoke new fill_constant kernel, the place of OpKernelType
    // will be setted by force_cpu and place_type here.
    if (ctx.Attr<bool>("force_cpu")) {
      kt.set_backend(phi::Backend::CPU);
    }
    auto place_type = ctx.Attr<int>("place_type");
    if (place_type != -1) {
      switch (place_type) {
        case 0:
          kt.set_backend(phi::Backend::CPU);
          break;
        case 1:
        case 2:
          kt.set_backend(phi::Backend::GPU);
          break;
        case 3:
          kt.set_backend(phi::Backend::XPU);
          break;
        case 4:
          kt.set_backend(phi::Backend::NPU);
          break;
        default:
          PADDLE_THROW(platform::errors::Unimplemented(
              "Could NOT determine the place of variable, place_type = %d .",
              place_type));
      }
    }

    return kt;
  }
};
```

## paddle 测试

使用空 shape []，会生成一个 0-D tensor


![image](https://user-images.githubusercontent.com/30856589/229082169-5e0bc0bf-8595-4f7f-b184-d7defd561ea1.png)

**Comment by FisherWY** [comment]
改一下`fill_constant`算子的`InferShape`方法后无Core dump

```
std::vector<shape_t> InferShapeForFillConstant(const std::vector<shape_t> &inputs_shape,
                                               const framework::AttrMapType &attrs) {
  CHECK(attrs.count("shape"));
  auto shape = absl::get<std::vector<int>>(attrs.at("shape"));
  // CHECK(!shape.empty()) << "shape attr is empty!";
  if (shape.empty()) {
    return {{1}};
  }
  return {shape};
}
```

但是会有新的错误，目测不是CINN的问题

```
I0331 12:09:30.874068 13931 build_cinn_pass.cc:682] --- [build_cinn_pass] detected 97 cinn supported subgraphs
Traceback (most recent call last):
  File "examples/cylinder/3d_unsteady_discrete/baseline/cylinder3d_unsteady.py", line 172, in <module>
    checkpoint_path=checkpoint_path + str(next_time) + "/")
  File "/home/wengyu02/work/PaddleScience/paddlescience/solver/solver.py", line 167, in solve
    num_epoch, bs, checkpoint_freq, checkpoint_path
  File "/home/wengyu02/work/PaddleScience/paddlescience/solver/solver.py", line 645, in __solve_static
    rslt = self.exe.run(compiled_program, feed=feeds, fetch_list=fetches)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/executor.py", line 1458, in run
    use_prune=use_prune,
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/executor.py", line 1661, in _run_impl
    scope, list(feed.keys()), fetch_list, return_numpy
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/executor.py", line 683, in run
    scope, feed_names, fetch_list
NotImplementedError: In user code:

    File "examples/cylinder/3d_unsteady_discrete/baseline/cylinder3d_unsteady.py", line 154, in <module>
      solver = psci.solver.Solver(pde=pde_disc, algo=algo, opt=opt)
    File "/home/wengyu02/work/PaddleScience/paddlescience/solver/solver.py", line 143, in __init__
      self.__init_static()
    File "/home/wengyu02/work/PaddleScience/paddlescience/solver/solver.py", line 584, in __init_static
      self.opt.minimize(self.loss)
    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 351, in _decorate_function
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/optimizer/optimizer.py", line 1436, in minimize
      no_grad_set=no_grad_set,
    File "/usr/local/lib/python3.7/dist-packages/paddle/optimizer/optimizer.py", line 1123, in backward
      [loss], parameter_list, act_no_grad_set, callbacks
    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 560, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/optimizer/optimizer.py", line 64, in append_backward_new
      orig2prim(block)
    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 560, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/incubate/autograd/primx.py", line 763, in orig2prim
      _lower(block, reverse=False, blacklist=[])
    File "/usr/local/lib/python3.7/dist-packages/paddle/incubate/autograd/primx.py", line 523, in _lower
      attrs=attrs,
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2980, in __init__
      for frame in traceback.extract_stack():

    UnimplementedError: Prim operator pow_p should not be excuted directly (at /home/wengyu02/work/Paddle/paddle/fluid/operators/prim_ops/pow_p_op.cc:30)
      [operator < pow_p > error]
```

**Comment by FisherWY** [comment]
更新，把`FLAGS_allow_cinn_ops`清空后（即允许使用CINN中的所有算子），就能正常跑通了

<img width="821" alt="image" src="https://user-images.githubusercontent.com/32707008/229147032-ac10d700-2c35-479b-b98d-635661c5a527.png">
